# Welcome to Jekyll!
#

# Site settings
pagetitle: Sterblue
title: Sterblue
subtitle: Automate your inspections
description:
owner: Sterblue # or company name
author: Sterblue # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: webmaster@sterblue.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sterblue.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/sterblue
  linkedin-square: https://www.linkedin.com/company/sterblue
  facebook-official: https://www.facebook.com/Sterblue.SAS
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:contact@sterblue.com?Subject=Message%20from%20website
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
include:  [".htaccess","CNAME"]
incremental: false
sass:
 style: compressed
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
